#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

if [ "$WM_PROJECT_DIR" == "" ] ; then
   source etc/bashrc
   echo "$WM_PROJECT_DIR"
fi

if [ "$PWD" != "$WM_PROJECT_DIR" ] ; then
    echo "Error: Current directory is not \$WM_PROJECT_DIR"
    echo "    The environment variable are not consistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and (un)source them."
    exit 1
fi

msInst=${msInst:-$1}
msInst=${msInst:-../..}
echo "msInst: '${msInst}'"

mkdir -p ${msInst}/bin/foamx4m
mkdir -p ${msInst}/lib

cp  $FOAM_APPBIN/*  ${msInst}/bin/foamx4m   || echo "not built"
cp  $FOAM_LIBBIN/*  ${msInst}/lib/          || echo "not built"
